### ISSUE TITLE
I can't fix this issue

### ISSUE THREAD

**Issue by tFlorian35** [PaulSolt/Contacts-App---Live-Stream#1]
I don't know is wrong this this code

![contactbug1](https://cloud.githubusercontent.com/assets/10777028/8195451/e4de81ce-1482-11e5-87f4-3039cac92ac4.png)
![contactbug2](https://cloud.githubusercontent.com/assets/10777028/8195452/e50252de-1482-11e5-877d-e87873432d21.png)

**Comment by PaulSolt** [comment]
Change to as! on the end. Changes to Swift 1.2 are the reason for the error. That will force the AnyObject to become a String type. This particular method will always return a String as the first entry for the documents directory.

[0] as! String
